name: Build and release Workflows

on:
  push:
    paths:
      - "build_ts/*"
      - "specs/*"
      - "!package.json"
    branches:
      # We only want to create a new release when
      # - a pr is merged to main
      # - we push into main
      - "main"
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_RUN_WORKFLOW_PAT }}
        # Install all dependencies
      - name: install
        run: npm --prefix build_ts/ install
        # Transpile all specs from ts to js
      - name: build
        run: npm --prefix build_ts/ run build

    # Need to tell it the path to the build_ts
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RUN_WORKFLOW_PAT }}
          PACKAGEJSON_DIR:  'build_ts'
          TARGET-BRANCH: 'main'
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}
          package: './build_ts/package.json'